#Service should not register with itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#port for Registry service
server:
  port: 8761

#Manaing the logging
logging:
  level:
      com.netflix.eureka: off
      com.netflix.discovery: off
