#GatwayUrl
#jwt:url: http://localhost:9093
  
#Appication Config
server:
  port: 9091
  error:
    whitelabel:
      enabled: false
feign:
  client:
    config:
      default:
        logger-level: full  
spring:
  application:
    name: Exchange-Rates-Microservice-Load
    
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        proc:
          param_null_passing: true
    
        ddl-auto: update
        generate-ddl: true      
  
#Eureka Config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost         
     
#logging.level.org.hibernate.SQL=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework=ERROR